export const READ_QUESTIONS_MAX = 102
export const READ_TOP_QUESTIONS_MAX = 12
export const MIN_NUM_OF_ANSWERS = 2
export const MAX_NUM_OF_ANSWERS = 10
export const QUESTION_INPUT_MIN_LENGTH = 15
export const QUESTION_INPUT_MAX_LENGTH = 100
export const ANSWER_INPUT_MAX_LENGTH = 100
export const QUESTION_KEYWORDS_MAX_LENGTH = 100
