image: node:14.5.0
cache:
  paths:
    - node_modules/
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
stages:
  - Security scans
  - Node.js image
  - AWS image
sast:
  stage: Security scans
  variables:
    SAST_DEFAULT_ANALYZERS: eslint, nodejs-scan
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
secret_detection_default_branch:
  stage: Security scans
  variables:
    SECRET_DETECTION_EXCLUDED_PATHS: node_modules
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
secret_detection:
  stage: Security scans
  variables:
    SECRET_DETECTION_EXCLUDED_PATHS: node_modules
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
Bundle:
  only:
    - master
    - '/^milestone#.*$/'
  stage: Node.js image
  artifacts:
    paths:
      - api
  script:
    - yarn install
    - yarn prettier
    - yarn tslint
    - yarn test
    - CI_COMMIT_SHA=$CI_COMMIT_SHA CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME yarn build
    - mkdir api
    - cp -r aws/. build api
    - cp ecosystem.config.js api/build
Deploy (master):
  only:
    - master
  stage: AWS image
  environment:
    name: Master
    url: https://ask-the-world-api-master-795011334.eu-central-1.elb.amazonaws.com/
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - Bundle
  script:
    - cd api
    - tar -cvf api.tar build scripts appspec.yml
    - aws s3 cp api.tar s3://ask-the-world-dev-release/master/
    - deploymentId=`aws deploy create-deployment --application-name ask-the-world-api-master
      --s3-location bucket=ask-the-world-dev-release,key=master/api.tar,bundleType=tar
      --deployment-group-name ask-the-world-api-master --output text`
    - aws deploy wait deployment-successful --deployment-id $deploymentId
Deploy (feature):
  only:
    - '/^milestone#.*$/'
  stage: AWS image
  environment:
    name: Feature
    url: https://ask-the-world-api-feature-422752572.eu-central-1.elb.amazonaws.com/
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - Bundle
  script:
    - cd api
    - tar -cvf api.tar build scripts appspec.yml
    - aws s3 cp api.tar s3://ask-the-world-dev-release/feature/
    - deploymentId=`aws deploy create-deployment --application-name ask-the-world-api-feature
      --s3-location bucket=ask-the-world-dev-release,key=feature/api.tar,bundleType=tar
      --deployment-group-name ask-the-world-api-feature --output text`
    - aws deploy wait deployment-successful --deployment-id $deploymentId
