image: node:14.5.0
cache:
  paths:
    - node_modules/
stages:
  - Node.js image
  - AWS image
Bundle:
  only:
    - master
    - /^milestone#.*$/
  stage: Node.js image
  artifacts:
    paths:
      - api
  script:
    - echo CI_COMMIT_SHA=$CI_COMMIT_SHA
    - export CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME
    - yarn install
    - yarn prettier
    - yarn tslint
    - yarn test
    - yarn build
    - mkdir api
    - cp -r aws/. build api
    - cp ecosystem.config.js api/build
Deploy:
  only:
    - master
  stage: AWS image
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - Bundle
  script:
    - cd api
    - tar -cvf api.tar build scripts appspec.yml
    - aws s3 cp api.tar s3://ask-the-world-dev-release/master/
    - deploymentId=`aws deploy create-deployment --application-name ask-the-world-api-master --s3-location bucket=ask-the-world-dev-release,key=master/api.tar,bundleType=tar --deployment-group-name ask-the-world-api-master --output text`
    - aws deploy wait deployment-successful --deployment-id $deploymentId
Deploy:
  only:
    - /^milestone#.*$/
  stage: AWS image
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - Bundle
  script:
    - cd api
    - tar -cvf api.tar build scripts appspec.yml
    - aws s3 cp api.tar s3://ask-the-world-dev-release/feature/
    - deploymentId=`aws deploy create-deployment --application-name ask-the-world-api-feature --s3-location bucket=ask-the-world-dev-release,key=feature/api.tar,bundleType=tar --deployment-group-name ask-the-world-api-feature --output text`
    - aws deploy wait deployment-successful --deployment-id $deploymentId
