image: node:14.5.0
cache:
  paths:
    - node_modules/
stages:
  - Node.js image
  - AWS image
Bundle:
  only:
    - master
    - /^milestone#.*$/
    - /^feature.*$/
  stage: Node.js image
  artifacts:
    paths:
      - api
  script:
    - yarn install
    - yarn prettier
    - yarn tslint
    - yarn unit
    - yarn test
    - CI_COMMIT_SHA=$CI_COMMIT_SHA CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME yarn build
    # - yarn seed-remote-dev
    - mkdir api
    - cp -r aws/. build api
    - cp env/ecosystem.config.js api/build
Deploy (master):
  only:
    - master
  stage: AWS image
  environment:
    name: Master
    url: https://ec2-18-194-139-71.eu-central-1.compute.amazonaws.com/api/
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - Bundle
  script:
    - cd api
    - tar -cvf api.tar build scripts appspec.yml
    - aws s3 cp api.tar s3://ask-the-world-dev-release/master/
    - deploymentId=`aws deploy create-deployment --application-name ask-the-world-api-master
      --s3-location bucket=ask-the-world-dev-release,key=master/api.tar,bundleType=tar
      --deployment-group-name ask-the-world-api-master --file-exists-behavior OVERWRITE --output text`
    - aws deploy wait deployment-successful --deployment-id $deploymentId
Deploy (feature):
  only:
    - /^milestone#.*$/
    - /^feature.*$/
  stage: AWS image
  environment:
    name: Feature
    url: https://ec2-18-196-70-139.eu-central-1.compute.amazonaws.com/api/
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - Bundle
  script:
    - cd api
    - tar -cvf api.tar build scripts appspec.yml
    - aws s3 cp api.tar s3://ask-the-world-dev-release/feature/
    - deploymentId=`aws deploy create-deployment --application-name ask-the-world-api-feature
      --s3-location bucket=ask-the-world-dev-release,key=feature/api.tar,bundleType=tar
      --deployment-group-name ask-the-world-api-feature --file-exists-behavior OVERWRITE --output text`
    - aws deploy wait deployment-successful --deployment-id $deploymentId
