export const READ_QUESTIONS_MAX = 25
export const NUM_OF_TOP_QUESTIONS = 25
export const MIN_NUM_OF_ANSWERS = 2
export const MAX_NUM_OF_ANSWERS = 10
export const QUESTION_INPUT_MIN_LENGTH = 30
export const QUESTION_INPUT_MAX_LENGTH = 100
export const ANSWER_INPUT_MAX_LENGTH = 50
export const QUESTION_KEYWORDS_MAX_LENGTH = 50
