export const READ_QUESTIONS_MAX = 99
export const MIN_NUM_OF_ANSWERS = 2
export const MAX_NUM_OF_ANSWERS = 8
export const QUESTION_INPUT_MIN_LENGTH = 30
export const QUESTION_INPUT_MAX_LENGTH = 100
export const ANSWER_INPUT_MAX_LENGTH = 50
export const QUESTION_KEYWORDS_MAX_LENGTH = 50
