version: 0.0
os: linux
files:
  - source: build
    destination: /home/ubuntu/ask-the-world-api
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
  ApplicationStart:
    - location: scripts/start.sh
