version: 0.0
os: linux
files:
  - source: build
    destination: /home/ubuntu/ask-the-world-api
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
  ValidateService:
    - location: scripts/validate.sh
      runas: ubuntu
